spring:
  application:
    name: itoken-config
  boot:
    admin:
      client:
        url: http://192.168.11.130:8084
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitlab.com/itokend/itoken-config.git
          search-paths: respo
          username: 870507307@qq.com
          password: zxcvbnm120
  zipkin:
    base-url: http://192.168.11.130:9411

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.11.130:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info